create table positions (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    rank_order integer not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp
);

create table organizations (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    parent_id bigint references organizations (id),
    level_no integer not null,
    sort_order integer not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp
);

create table users (
    id bigint generated by default as identity primary key,
    login_id varchar(100) not null unique,
    external_subject varchar(255),
    password_hash varchar(255) not null,
    name varchar(100) not null,
    email varchar(255) not null,
    organization_id bigint not null references organizations (id),
    position_id bigint not null references positions (id),
    roles varchar(255) not null,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp
);

create table approval_types (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    description varchar(500),
    active boolean not null default true
);

create table approval_lines (
    id bigint generated by default as identity primary key,
    approval_type_id bigint not null references approval_types (id),
    name varchar(100) not null,
    active boolean not null default true
);

create table approval_line_steps (
    id bigint generated by default as identity primary key,
    approval_line_id bigint not null references approval_lines (id),
    step_order integer not null,
    step_type varchar(50) not null,
    organization_scope varchar(50),
    position_id bigint references positions (id),
    direct_user_id bigint references users (id),
    sort_policy varchar(50) not null default 'POSITION_ORDER',
    unique (approval_line_id, step_order)
);

create table approval_org_exceptions (
    id bigint generated by default as identity primary key,
    approval_type_id bigint not null references approval_types (id),
    organization_id bigint not null references organizations (id),
    approver_user_id bigint not null references users (id),
    step_order integer not null,
    active boolean not null default true
);

create table applications (
    id bigint generated by default as identity primary key,
    applicant_id bigint not null references users (id),
    approval_type_id bigint not null references approval_types (id),
    application_date date not null,
    receipt_date date not null,
    vendor varchar(200) not null,
    amount numeric(15, 2) not null,
    description text not null,
    status varchar(50) not null,
    submitted_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp
);

create table application_approval_steps (
    id bigint generated by default as identity primary key,
    application_id bigint not null references applications (id),
    step_order integer not null,
    original_approver_id bigint not null references users (id),
    status varchar(50) not null,
    acted_at timestamptz,
    unique (application_id, step_order)
);

create table approval_histories (
    id bigint generated by default as identity primary key,
    application_id bigint not null references applications (id),
    approval_step_id bigint references application_approval_steps (id),
    action varchar(50) not null,
    original_approver_id bigint references users (id),
    actor_id bigint not null references users (id),
    admin_override boolean not null default false,
    admin_reason text,
    comment text,
    acted_at timestamptz not null default current_timestamp
);

create table attachments (
    id bigint generated by default as identity primary key,
    application_id bigint not null references applications (id),
    original_filename varchar(255) not null,
    stored_filename varchar(255) not null,
    file_path varchar(1000) not null,
    mime_type varchar(100) not null,
    file_size bigint not null,
    uploaded_by bigint not null references users (id),
    uploaded_at timestamptz not null default current_timestamp
);

create table notification_events (
    id bigint generated by default as identity primary key,
    recipient_id bigint not null references users (id),
    application_id bigint references applications (id),
    notification_type varchar(50) not null,
    channel varchar(50) not null,
    title varchar(200) not null,
    body text not null,
    status varchar(50) not null,
    read_flag boolean not null default false,
    sent_at timestamptz,
    failed_reason text,
    template_code varchar(100),
    external_message_id varchar(255),
    created_at timestamptz not null default current_timestamp
);
