create table calendar_events (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    description text,
    location varchar(200),
    start_at timestamptz not null,
    end_at timestamptz not null,
    all_day boolean not null default false,
    created_by_id bigint not null references users (id),
    updated_by_id bigint references users (id),
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    constraint calendar_events_time_range check (end_at > start_at)
);

create index idx_calendar_events_range on calendar_events (start_at, end_at);
