create table user_organizations (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id),
    organization_id bigint not null references organizations (id),
    primary_flag boolean not null default false,
    sort_order integer not null default 10,
    active boolean not null default true,
    created_at timestamptz not null default current_timestamp,
    unique (user_id, organization_id)
);

create unique index ux_user_organizations_active_primary
    on user_organizations (user_id)
    where primary_flag = true and active = true;

insert into user_organizations (user_id, organization_id, primary_flag, sort_order, active)
select id, organization_id, true, 10, true
from users;

alter table applications
    add column approval_organization_id bigint references organizations (id);

update applications app
set approval_organization_id = users.organization_id
from users
where users.id = app.applicant_id
  and app.approval_organization_id is null;

alter table applications
    alter column approval_organization_id set not null;

with inserted_root as (
    insert into organizations (name, parent_id, level_no, sort_order, active)
    select '더이음사랑의교회', null, 1, 10, true
    where not exists (
        select 1
        from organizations
        where name = '더이음사랑의교회'
          and parent_id is null
    )
    returning id
),
selected_root as (
    select id
    from inserted_root
    union all
    select id
    from organizations
    where name = '더이음사랑의교회'
      and parent_id is null
    order by id
    limit 1
),
departments as (
    select *
    from (
        values
            ('예배부', 10),
            ('총무부', 20),
            ('재정부', 30),
            ('미래준비부', 40)
    ) as department(name, sort_order)
)
insert into organizations (name, parent_id, level_no, sort_order, active)
select departments.name, selected_root.id, 2, departments.sort_order, true
from departments
cross join selected_root
where not exists (
    select 1
    from organizations existing
    where existing.name = departments.name
      and existing.parent_id = selected_root.id
);

with selected_root as (
    select id
    from organizations
    where name = '더이음사랑의교회'
      and parent_id is null
    order by id
    limit 1
),
teams as (
    select *
    from (
        values
            ('예배부', '찬양팀', 10),
            ('예배부', '미디어팀', 20),
            ('예배부', '새가족팀', 30),
            ('예배부', '중보기도팀', 40),
            ('총무부', '기획팀', 10),
            ('총무부', '시설팀', 20),
            ('재정부', '회계팀', 10),
            ('재정부', '감사팀', 20),
            ('미래준비부', '이음씨드', 10),
            ('미래준비부', '이음키즈', 20)
    ) as team(parent_name, name, sort_order)
),
selected_departments as (
    select teams.parent_name, min(department.id) as id
    from teams
    join selected_root on true
    join organizations department on department.name = teams.parent_name
        and department.parent_id = selected_root.id
    group by teams.parent_name
)
insert into organizations (name, parent_id, level_no, sort_order, active)
select teams.name, selected_departments.id, 3, teams.sort_order, true
from teams
join selected_departments on selected_departments.parent_name = teams.parent_name
where not exists (
    select 1
    from organizations existing
    where existing.name = teams.name
      and existing.parent_id = selected_departments.id
);

select setval(
    pg_get_serial_sequence('organizations', 'id'),
    coalesce((select max(id) from organizations), 1),
    (select max(id) is not null from organizations)
);
select setval(
    pg_get_serial_sequence('user_organizations', 'id'),
    coalesce((select max(id) from user_organizations), 1),
    (select max(id) is not null from user_organizations)
);
